### ISSUE TITLE
Pagination support is planned? 

### ISSUE THREAD

**Issue by alejandrozf** [adamwynne/twitter-api#76]
I've been trying to use this library, and I think is a quite nice interface to Twitter API but I didn't found a way to abstract the pagination that would be helpful when is needed to get a lot of results; for example 'user_timeline', 'home_timeline', etc. 

An approach like tweepy (Python library) [does](https://github.com/tweepy/tweepy/blob/cd46550b3ef068857f5de9c37bbdd0a72acb7462/docs/cursor_tutorial.rst) could be awesome.

**Comment by chbrown** [comment]
Hi @alejandrozf, actually I've found that Clojure's lazy sequences allow for syntax that's even nicer than Python's/Tweepy's.

My fork/v2.0 of `twitter-api`, [`twttr`](https://github.com/chbrown/twttr), supports just the same raw API calls that `twitter-api` does, but I've been knocking around a helper library that composes/layers those calls in useful ways, calling it [`twttr-ops`](https://github.com/chbrown/twttr-ops). E.g., this one, to lazily iterate through a user's full timeline: https://github.com/chbrown/twttr-ops/blob/9cd8c1e/src/twttr/ops.clj#L93-L111

There's a pretty big difference between `twitter-api` and `twttr` that makes this work more nicely in the latter: in `twttr` the `(api/* ...)` calls return the parsed response body with the response headers and status attached to the result's (whether hash-map or seq) metadata, whereas with `twitter-api` you'd have to concat the `:body` of each page, rather than each page directly.

**Comment by chbrown** [comment]
Closing as out-of-scope for this particular library.
